// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hjrfosdprublctmasoiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhqcmZvc2RwcnVibGN0bWFzb2l3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTA5MjcsImV4cCI6MjA3MTI4NjkyN30.VdI6S0WAsfNE5wlbPkCi7vZoM4zOsdAspURInUeVaPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});